name: Building GSI..

on: [push]

env:
  ROM_URL: https://cloud.minati.workers.dev/dotOS-R-v5.1-RMX1941-UNOFFICIAL-20210529-2316.zip 
  ROM_NAME: Generic:Dot-old
  ZIP_NAME: Ftest.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk expect xmlstarlet make aapt
       
       - name: Clone
         run: |
            git clone https://github.com/rahulkhatri137/vendor_hardware_overlay treble
            cd treble ; ls
       
       - name: Framework
         run: |
            cd treble
            bash ./build/build.sh treble-overlay-realme-1
            ls
       
       - name: Zip AB and upload 
         run: |
              cd treble ; cd build ; ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.apk\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
