name: Fix prop

on: [push]

env:
  URL : "https://dipeshmirror.dipeshtech.workers.dev/0:/system-squeak-arm64-ab-vndklite-gapps.img.xz"
  ZIP_NAME : ""
  TZ: Asia/Kolkata
jobs:
  Merge:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo apt install expect simg2img p7zip aria2 -y
       
       - name: Download & Extract
         continue-on-error: true
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" $URL
            xz -d *xz ; rm -rf *zip *7z *xz ; ls
            mkdir -p a ; ls ; e2fsck -pf *img
            
       - name: Mount
         run: |
            sudo mount -o loop,rw,sync *.img a
            
       - name: Fix prop
         continue-on-error: true
         run: |
            cd a/system ; sudo chmod -R 777 build.prop
            sudo echo "" >> build.prop
            sudo echo "# Don't write binary XML files" >> build.prop
            sudo echo "persist.sys.binary_xml=false" >> build.prop
            sudo echo "" >> build.prop
            sudo cat build.prop ; sudo chmod 0600 build.prop
            cd ../.. ; e2fsck -yf *img

       - name: Repack
         run: |
            sudo umount a ; sudo chmod -R 777 *img ; gzip -fq9 *img ; mkdir final ; mv *gz final

       - name: Upload
         run: |
            cd final ; ls 
            expect -c " 
            spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
            expect \"yes/no\"
            send \"yes\r\"
            expect \"Password\"        
            send \"${{ secrets.SFPASS }}\r\"
            expect \"sftp> \"
            send \"cd ${{ secrets.SFDIR }}\r\"
            set timeout -1
            send \"cd port\r\"
            set timeout -1
            send \"put *\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            send \"bye\r\"
            interact"
