name: Building GSI..

on: [push]

env:
  URL: https://mirror2.rahul137.workers.dev/framework-res.apk
  ZIP : Dot-F.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk aria2 expect xmlstarlet make
       
       - name: Clone
         run: |
            git clone https://github.com/rahulkhatri137/treble_experimentations treble
            mv frm ./treble ; cd treble ; ls ; mkdir -p system ; cd system ; mkdir -p framework ; cd framework
            aria2c $URL
       
       - name: Extract Framework
         run: |
            cd treble
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar ; ls
            bash ./overlay/generate.sh system frm
            ls ; cd system ; cd framework ; ls
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar ; ls
            java -jar apktool_2.5.0.jar framework-res.apk
            ls
            
       - name: Update values
         run: |
              cd
       
       - name: Repack and upload 
         run: |
              cd ./treble/system/framework/framework-res ; ls
              zip -r $ZIP *
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
