name: Building GSI..

on: [push]

env:
  ROM_URL: https://cloud.minati.workers.dev/dotOS-R-v5.1-RMX1941-UNOFFICIAL-20210529-2316.zip 
  ROM_NAME: Generic:Dot-old
  ZIP_NAME: Dot-old-RK137GSI.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           sudo apt install expect -y
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect
       
       - name: Clone
         run: |
            git clone https://github.com/rahulkhatri137/treble_experimentations treble
            cd treble ; mkdir -p system ; cd system ; mkdir -p framework ; cd framework
            wget https://mirror.rahul137.workers.dev/framework-res.apk
       
       - name: Framework
         run: |
            cd treble ; cd overlay
            bash generate.sh system frm
            ls
       
       - name: Zip AB and upload 
         run: |
              cd ./treble/framework
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put n\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
