name: Building GSI..

on: [push]

env:
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git expect xmlstarlet dos2unix

       
       - name: Clone repo
         run: git clone --recurse-submodules https://github.com/rahulkhatri137/vendor_hardware_overlay vo
       
       - name: Zip overlays
         run: |
              mkdir output
              sudo chmod -R 777 vo ; cd vo/build ; bash build.sh ; bash ./../tests/tests.sh ; bash org.sh
              cp -frp a/* ./../../output ; cd ../../
              export date=`date +%Y%m%d`
              sudo chmod -R 777 output
              cd output ; ls
              zip -r overlays-$date.zip *

       - name: Upload 
         uses: softprops/action-gh-release@v1
         with:
           files: output/overlays*.zip
           name: Overlays
           tag_name: release
           #body: Use actions auto bulid
         env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
