name: Merge vndk28

on: [push]

env:
  URL : https://udomain.dl.sourceforge.net/project/nippongsi/AOSP%20-%20CipherOS-2.0%20-%20HXXMTHQZNW/CipherOS-2.0-AB-12-20211007-nippongsi.img.gz
  ZIP_NAME : test.gz
  TZ: Asia/Kolkata
jobs:
  Merge:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo apt install expect simg2img aria2c -y
       
       - name: Download
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -o $ZIP_NAME $URL
            gz -d $ZIP_NAME
            
       - name: Extract
         run: |
            mkdir -p a ; ls
            sudo mount -o rw,sync 
            
       - name: Update values
         run: |
            cd final
            mv -f power_profile.xml ../framework/framework-res/res/xml
            rm -rf ../framework/framework-res/res/values/styles.xml
            mv -f styles.xml ../framework/framework-res/res/values

       - name: Repack
         run: |
            cd framework/framework-res ; ls ; cd .. ; rm -rf framework-res.apk
            java -jar apktool_2.5.0.jar b -f framework-res
            ls 

       - name: Upload
         run: |
            cd final ; ls 
            expect -c " 
            spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
            expect \"yes/no\"
            send \"yes\r\"
            expect \"Password\"        
            send \"${{ secrets.SFPASS }}\r\"
            expect \"sftp> \"
            send \"cd ${{ secrets.SFDIR }}\r\"
            set timeout -1
            send \"put *.apk\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            send \"bye\r\"
            interact"
