name: Debloat

on: [push]

env:
  URL : https://master.dl.sourceforge.net/project/sgsi137/Test/cos_1.img?viasf=1
  TZ: Asia/Kolkata
jobs:
  Merge:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo apt update; sudo apt install tree git expect simg2img p7zip aria2 -y
       
       - name: Download & Extract
         continue-on-error: true
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" $URL
            simg2img *.img cos.img; mkdir -p a ; ls ; e2fsck -pf *img
            
       - name: Mount
         run: |
            sudo mount -o loop,rw,sync cos.img a
            
       - name: Get tree
         continue-on-error: true
         run: |
            tree a/system > cos_1_tree.txt

       - name: Upload
         run: |
            expect -c " 
            spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
            expect \"yes/no\"
            send \"yes\r\"
            expect \"Password\"        
            send \"${{ secrets.SFPASS }}\r\"
            expect \"sftp> \"
            send \"cd /home/pfs/project/sgsi137\r\"
            set timeout -1
            send \"cd Test\r\"
            set timeout -1
            send \"put *.txt\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            send \"bye\r\"
            interact"
