name: Pack oss vendor

on: [push]

env:
  NAME: Cipher-vndk31-20220221
  URL: https://cloud.minati.workers.dev/CipherOS-2.5-LYNX-cipher_CPH1859-20220221-1637-UNOFFICIAL-VANILLA.zip
  TZ: Asia/Kolkata
jobs:
  Work:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Initializing environment
         run: |
            sudo apt install expect aria2 -y
            
       - name: Download
         run: |
              aria2c -c --max-tries=0 --max-file-not-found=0 $URL
              unzip *.zip ; ls final
              mv vendor* final ; mv *list final
       
       - name: Repack
         run: |
              cd final; ls
              zip -r $NAME.zip *
              ls
   
       - name: Upload 
         run: |
              cd final ; ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR2 }}\r\"
              set timeout -1
              send \"put *zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
