name: Extract apk source

on: [push]

env:
  URL: 
  ROM_NAME: Generic:Dot-old
  ZIP_NAME: terminal.zip
  TZ: Asia/Kolkata
jobs:
  Extract:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk aria2 expect xmlstarlet make
       
       - name: Clone
         run: |
            mkdir -p apk ; cd apk
       
       - name: Apktool
         run: |
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar ; ls
            java -jar apktool_2.5.0.jar d -f terminal.apk ; ls
       
       - name: Zip Source and upload 
         run: |
              sudo chmod -R 777 terminal ; cd terminal ; ls
              zip -r $ZIP_NAME *
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
