name: Building GSI..

on: [push]

env:
  ROM_URL: https://cloud.minati.workers.dev/dotOS-R-v5.1-RMX1941-UNOFFICIAL-20210529-2316.zip 
  ROM_NAME: Generic:Dot-old
  ZIP_NAME: Dot-old-RK137GSI.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk aria2 expect xmlstarlet make
       
       - name: Clone
         run: |
            git clone https://github.com/rahulkhatri137/treble_experimentations treble
            mv frm ./treble ; cd treble ; ls ; mkdir -p system ; cd system ; mkdir -p framework ; cd framework
            aria2c https://mirror.rahul137.workers.dev/framework-res.apk
       
       - name: Framework
         run: |
            cd treble
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar ; ls
            bash ./overlay/generate.sh system frm
            ls ; cd system ; cd framework ; ls
       
       - name: Zip AB and upload 
         run: |
              cd ./treble/rro ; ls
              make Android.mk ; ls
              cd zip
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put n\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
