name: Building GSI..

on: [push]

env:
  URL: https://mirror.rahul137.workers.dev/ScriptRunner_v1.3_apkpure.com.apk
  ROM_NAME: Generic:Dot-old
  ZIP_NAME: script.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk aria2 expect xmlstarlet make
       
       - name: Clone
         run: |
            mkdir -p apk ; cd apk
            aria2c $URL
       
       - name: Framework
         run: |
            cd apk
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar ; ls
            java -jar apktool_2.5.0.jar -d ScriptRunner_v1.3_apkpure.com.apk ; ls
       
       - name: Zip AB and upload 
         run: |
              cd apk/ScriptRunner_v1.3_apkpure.com
              zip -r $ZIP_NAME *
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
