name: Extract Image

on: [push]

env:
  URL: https://managedway.dl.sourceforge.net/project/gsis137/port/L-oss-f.zip 
  NAME: Dot-oss
  URL2: https://newcontinuum.dl.sourceforge.net/project/realme-1/DotOS/dotOS-R-v5.2-CPH1859-UNOFFICIAL-20210916-1553.zip
  TZ: Asia/Kolkata
jobs:
  Work:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Initializing environment
         run: |
            sudo apt install expect aria2 -y
       
       - name: Setup
         run: |
            aria2c -c --max-tries=0 --max-file-not-found=0 $URL; mkdir -p final; unzip -q *.zip -d ./final; cd final; rm -rf vendor*
       
       - name: Download
         run: |
              rm -rf *zip ; aria2c -c --max-tries=0 --max-file-not-found=0 $URL2
              unzip *.zip ; ls final
              mv vendor* final
       
       - name: Repack
         run: |
              cd final; ls
              zip -r $NAME.zip *
              ls ; mkdir -p final ; mv *zip final
   
       - name: Upload 
         run: |
              cd final/final ; ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR2 }}\r\"
              set timeout -1
              send \"put *\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
