name: Merge vndk28

on: [push]

env:
  URL : https://managedway.dl.sourceforge.net/project/gsitutorials-sgsi/SGSI/A12Beta/Pixel3-SP1A-A12-SGSI-GSI-Tutorials.7z
  ZIP_NAME : test.7z
  TZ: Asia/Kolkata
jobs:
  Merge:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            docker rmi `docker images -q`
            sudo apt install expect simg2img p7zip aria2 coreutils -y
       
       - name: Download
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -o $ZIP_NAME $URL
            7z x $ZIP_NAME ; ls ; rm -rf *zip *7z
            
       - name: Extract
         run: |
            mkdir -p a ; ls ; e2fsck -pf *img ; df -h
            sudo mount -o rw,sync *.img a ; df -h
            
       - name: Add vndk28
         run: |
            sudo cp -fr *.apex a/system/apex/
            ls a/system/apex
            ln -s  /apex/com.android.vndk.v28/lib a/system/system/lib/vndk-28
            ln -s  /apex/com.android.vndk.v28/lib64 a/system/system/lib64/vndk-28
            ln -s  /apex/com.android.vndk.v28/lib a/system/system/lib/vndk-sp-28
            ln -s  /apex/com.android.vndk.v28/lib64 a/system/system/lib/vndk-sp-28

       - name: Repack
         run: |
            e2fsck -pyf *img ; gzip *img ; mkdir final ; mv *gz final/

       - name: Upload
         run: |
            cd final ; ls 
            expect -c " 
            spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
            expect \"yes/no\"
            send \"yes\r\"
            expect \"Password\"        
            send \"${{ secrets.SFPASS }}\r\"
            expect \"sftp> \"
            send \"cd ${{ secrets.SFDIR }}\r\"
            set timeout -1
            send \"put *\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            send \"bye\r\"
            interact"
