name: Updating framework

on: [push]

env:
  URL: https://mirror.rahul137.workers.dev/framework-res.apk
  ZIP : Fluid-Ft.zip
  TZ: Asia/Kolkata
jobs:
  Framework:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk aria2 expect xmlstarlet make
       
       - name: Download
         run: |
            ls ; mkdir -p framework ; cd framework
            aria2c $URL
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar

       - name: Extract Framework
         run: |
            cd framework
            java -jar apktool_2.5.0.jar d -f framework-res.apk
            ls ; cd framework-res ; ls
            
       - name: Update values
         run: |
            cd frm
            mv -f power_profile.xml ../framework/framework-res/res/xml
            rm -rf ../framework/framework-res/res/values/styles.xml
            mv -f styles.xml ../framework/framework-res/res/values

       - name: Repack
         run: |
            cd framework/framework-res ; ls ; cd .. ; rm -rf framework-res.apk
            java -jar apktool_2.5.0.jar b -f framework-res
            ls ; cd framework-res ; ls ; cd build ; ls ; cd apk ; ls
            cd ../dist ; ls

       - name: Upload
         run: |
            cd ./framework/framework-res/dist ; ls 
            expect -c " 
            spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
            expect \"yes/no\"
            send \"yes\r\"
            expect \"Password\"        
            send \"${{ secrets.SFPASS }}\r\"
            expect \"sftp> \"
            send \"cd ${{ secrets.SFDIR }}\r\"
            set timeout -1
            send \"put *.apk\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            send \"bye\r\"
            interact"
